name: Build and Release

on:
  push:
    tags:
      - 'v*' # 只有推送以'v'开头的标签时，才会触发此工作流

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 为默认的GITHUB_TOKEN赋予写入仓库内容的权限，这是创建Release所必需的[citation:1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # 拉取你的代码到虚拟环境

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew build # 运行Gradle构建任务，这会在build/libs/目录下生成JAR文件

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2 # 一个流行的创建Release的Action[citation:10]
      with:
        files: |
          build/libs/*.jar # 上传build/libs/目录下所有的JAR文件
        generate_release_notes: true # 可选：让GitHub自动生成发布说明[citation:10]
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用GitHub自动提供的令牌
